filebeat.inputs:
- type: filestream
  id: systemlog 
  paths:
    - /var/log/auth.log
  tags: ['systemlog']    
    
- type: filestream
  id: syslog
  paths:
    - /var/log/syslog
  tags: ['syslog']    


output.logstash:
  hosts: ['192.168.57.4:5044']
